---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: 705931391253.dkr.ecr.us-east-2.amazonaws.com/spring-tasks-service:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 30202
      imagePullSecrets: 
      - name: spring-login-secret

---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
  - port: 30202
    targetPort: 30202
  type: LoadBalancer

