name: Deploy to ECR

on:
  push:
    branches: [ "docker" ]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: build
      run: mvn --batch-mode -DskipTests package
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build & tag image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: spring-login
        IMAGE_TAG: spring-login:$(date +%s)
      run: cd spring-login/ && docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - name: Push image to Amazon ECR
      run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
